## NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great StackOverflow post

In this notebook we will cover only the basic concepts that will help us build on further concepts through exprience. Mainly we will cover 
* Numpy arrays
* Numpy indexing and selection and selected
* Numpy operations
Numpy is extremely fast and other data analysis libraries relpy mostly on numpy.


* Numpy arrays - arrays are faster and  simpler
Numpy arrays can come in one dimensional array or two dimensional matrices

In [2]:
# We neen to import numpy before we can use it
import numpy as np # np is an instance of numpy library

In [2]:
# We can create a numpy array using the following command
arr = np.array([1,2,3,4,5]) # one dimentional array
arr

array([1, 2, 3, 4, 5])

In [4]:
two_dime_arr = np.array([[1,2,3,4],[5,6,7,8],[2,4,7,8]])
two_dime_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 7, 8]])

In [6]:
# we can also create a list and transfor, it to a numpy array
my_list = [[20,3,45], [4,10,43]]
t_arr = np.array(my_list)
t_arr

array([[20,  3, 45],
       [ 4, 10, 43]])

In [9]:
# Usually we use python built in generation methods
np.arange(10, 20) # we specify start and end for the range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(0,11,2) # o to 10 with step size 2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#Zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
#Also multidimensional
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# We can do  the same with ones
np.ones(10) # creates an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#Linesoace - to create uniformly spaced arrays 
# of given number in a given range
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [18]:
#We can use the eye function to create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#Creating rundom arrays of uniform distribution [0,1]
np.random.rand(5)

array([0.34224558, 0.26567926, 0.9059343 , 0.56895393, 0.00757899])

In [21]:
#Multidimensional randoms
np.random.rand(5,5)

array([[0.73388864, 0.01089505, 0.87591269, 0.57115127, 0.91444542],
       [0.06455402, 0.39628008, 0.31895541, 0.38231226, 0.71459084],
       [0.15068099, 0.11501621, 0.46918426, 0.36933237, 0.98886419],
       [0.69691367, 0.02745704, 0.8524039 , 0.75799217, 0.25118639],
       [0.74409483, 0.48234238, 0.33361147, 0.13507727, 0.85059174]])

In [28]:
#randn is used to create randoms ouy of the range [0,1]
np.random.randn(5,5)

array([[-1.27104007e+00,  1.60581389e-01,  1.12844191e+00,
        -1.14888346e-03, -2.19203633e+00],
       [-4.73311577e-01,  1.63516409e+00,  1.69557526e+00,
         1.33884304e+00, -8.11478374e-02],
       [ 6.32911111e-01,  1.89283787e+00, -2.51478524e-01,
        -2.23598589e-01, -1.92794086e-01],
       [ 1.20167524e-01,  5.35535917e-01,  4.57714832e-01,
        -1.02705115e+00, -8.83054768e-01],
       [-1.75633602e-01, -6.20220501e-01, -1.12987341e+00,
        -1.23788953e+00,  9.28332958e-01]])

In [29]:
#-we pass low, high and the numbr of elements
np.random.randint(1,100,10)

array([60, 77, 72, 77, 32, 87, 36, 72, 27, 32])

In [30]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
b = np.random.randint(0,50,10)
b

array([10, 14, 11, 41, 40, 13, 21, 18, 23, 45])

In [34]:
# We can cange the dimensions of an array using the reshape
a.reshape(5,5)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
#Maximum value 
a.max()

24

In [36]:
#min value
a.min()

0

In [37]:
# Index of max/min value
a.argmax()

24

In [38]:
a.argmin()

0

In [39]:
a.shape

(25,)

In [40]:
c = a.reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
c.shape

(5, 5)

In [43]:
a.dtype

dtype('int32')

In [45]:
# We can also separately import the library we want from munpy
from numpy.random import randint # example

In [46]:
randint(2,10)

7

# Numpy indexing and Selection

In [4]:
m = np.arange(0,11)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#If we want a value at index 2
m[2]

2

In [6]:
# We can also slice the array using starting and end indices
m[2:5]

array([2, 3, 4])

In [7]:
# Or we can slice every element up to 6
# We use the same slicing technique like in python
m[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
m[5:] # gives us every element after index 5

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# Broadcasting a value to a range of indices
m[:5] = 100 # This replaces all elements with lower index to 5 with 100
m

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
m = np.arange(0,11) # reset the array
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_ar = m[0:6]
slice_ar

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_ar[:] = 99 # overwrites every element
slice_ar

array([99, 99, 99, 99, 99, 99])

In [19]:
#Copying an array
ar_copy = m.copy()
ar_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
#We can use the same logic to index multi timensional arrays
arr_2d = np.array([[5,10,25],[20,5,12],[20,30,40]])
arr_2d

array([[ 5, 10, 25],
       [20,  5, 12],
       [20, 30, 40]])

In [25]:
#We can access a whole row (second) using single indexing
arr_2d[1]

array([20,  5, 12])

In [29]:
#We can index a specific element as follows
arr_2d[1,2]

12

In [30]:
# We can also access slice of elements using
# This gives us everything up to third row and from second column
arr_2d[:2,1:]

array([[10, 25],
       [ 5, 12]])

In [33]:
# If we want to retun every row up to the third row
arr_2d[:2]

array([[ 5, 10, 25],
       [20,  5, 12]])

In [35]:
# Using comparison operations
bool_arr = m > 5
bool_arr # retuns all arrays evaluated true in the conditional statement

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# Numpy Operations
* Array with array operations
* Array with Scalars operations
* Universal array functions

In [38]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# Array operations
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
# Division returs warning nan - division by zero still returns answer
arr / arr

C:\Users\dhest\AppData\Local\Temp\ipykernel_3048\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
# Array scalar operations
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [44]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [45]:
arr -1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [48]:
# exponents
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [49]:
#Other operations - square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [50]:
# Exponential other form
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [51]:
#Maximun or minimam
np.max(arr)

10

In [52]:
# Similarly we can return the max as 
arr.max()

10

In [53]:
# We can us the documantation of the numpy array universal functions
# documentation for forther operations 
#https://numpy.org/doc/stable/reference/ufuncs.html